version: '3'

services:
  swift:
    image: openstackswift/saio
    environment:
      - SWIFT_USERNAME=test:tester
      - SWIFT_PASSWORD=testing
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - swift_data:/srv
    networks:
      - swift_network

volumes:
  swift_data:

networks:
  swift_network:
