version: "3.8"

services:
  hadoop-postgres:
    image: postgres:13
    container_name: hadoop-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - :5432
    volumes:
      - hadoop_postgres_data:/var/lib/postgresql/data
    networks:
      - file-upload
      
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - file-upload

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - file-upload

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql://user:password@hadoop-postgres:5432/mydatabase
      - HADOOP_URL=http://hadoop-namenode:9870
    ports:
      - "8001:8000"
    depends_on:
      - hadoop-postgres
      - hadoop-namenode
    networks:
      - file-upload

volumes:
  hadoop_postgres_data:
  hadoop_namenode:
  hadoop_datanode:

networks:
  file-upload:
